version: "3"

tasks:
  dev:
    cmds:
      - uv run cereal --config config/dev.yaml

  lint:
    cmds:
      - uv run ruff format --check
      - uv run ruff check

  test:
    cmds:
      - uv run pytest

  check:
    cmds:
      - task: lint
      - uv run ty check
      - task: test
